name: Generate MATEJ Commit Art Daily

on:
  # Run every day at midnight UTC (adjust cron if needed)
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-art:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We disable credential persistence since we’ll force-push later.
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate commit art
        env:
          # The automatically provided GITHUB_TOKEN must have permission to force push.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 generate_art.py
